export const inputData = {
  text:{
    fieldname:"text",
    type:"text",
    required:false
  },
  number:{
    fieldname:"number",
    type:"number",
    required:false
  },
  email:{
    fieldname:"email",
    type:"email",
    required:false
  },
  website:{
    fieldname:"url",
    type:"text",
    required:false
  },
  date:{
    fieldname:"Date",
    type:"Date",
    required:false
  }
}